name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: git lfs install

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ vars.HF_USERNAME }}
          HF_SPACE: ${{ vars.HF_SPACE }}
        run: |
          git config user.email "ms.malmir@gmail.com"
          git config user.name  "momalmir"
          # Add or update the HF remote
          git remote remove hf || true
          git remote add hf https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE
          # Force-push current branch to Space main
          git push hf HEAD:main --force
